### ISSUE TITLE
The value 'undefined' does not exist for the field 'filter'

### ISSUE THREAD

**Issue by jbartko** [bluefrg/jira-grafana-json-datasource#1]
Hello! 

Thank you for sharing this project! It looks promising, but when attempting to use it calls to /test-jira appear to succeed, then when configuring a Grafana panel to use the datasource, I see errors like the following:
```
(node:24) UnhandledPromiseRejectionWarning: {
  "statusCode": 400,
  "body": {
    "errorMessages": [
      "The value 'undefined' does not exist for the field 'filter'."
    ],
...
  "request": {
    "uri": {
      "hostname": "JIRA.EXAMPLE.COM",
      "pathname": "/rest/api/2/search",
```
Current Jira version is 7.3.8. Might this project be expected to work with that version?

**Comment by mikefrank-ca** [comment]
Which version of Grafana are you running? I suspect Grafana isn't passing an array of `targets` in to the `/query` endpoint.

https://github.com/bluefrg/jira-grafana-json-datasource/blob/master/server.js#L109

**Comment by jbartko** [comment]
Currently deployed Grafana version for me is 5.2.1

**Comment by mikefrank-ca** [comment]
Exception was being thrown when adding a panel. Grafana was querying without a target. Grafana version was irrelevant. Give it a try now.
