### ISSUE TITLE
Metrics are not showing

### ISSUE THREAD

**Issue by DrEprom** [bluefrg/jira-grafana-json-datasource#13]
Hello bluefrg,
first of all I want to thank you for your wonderful work and sharing your Project.
I currently got the Problem, that when I want to select a metric, there is nothing to choose.
The /jira-test is working fine for me.
I'm using the jira cloud version and my current Grafana version is Grafana v7.0.3.
Thank you very much and have a wonderful day =).
![Github_Jira](https://user-images.githubusercontent.com/65225884/85109288-619ba580-b211-11ea-826a-0c89928f2fa1.jpg)

**Comment by bbgobie** [comment]
@DrEprom Any chance you fixed this and can share what you had to do? I have the same issue, with a 405 unhandled promise rejection warning
