### ISSUE TITLE
What needs to be done to use it on an ON-Prem instance?

### ISSUE THREAD

**Issue by Hornochs** [bluefrg/jira-grafana-json-datasource#14]
Hi there,

would it be possible to tell me what should be done to use it on an On-Prem Installation from JIRA Service Desk? Would be awesome 👍 

Cheers,
Hornochs

**Comment by mikefrank-ca** [comment]
I unfortunately don't have access to an on-prem JIRA to know or test with. But I encourage anyone to make a PR to support this.
