### ISSUE TITLE
Grafana not working

### ISSUE THREAD

**Issue by ramogundogdu** [bluefrg/jira-grafana-json-datasource#15]
I set up the envoirement with Docker v19.03.13 and my container is running on localhols:3000 . The grafana app should reachable but I get just following message:

`Mon Oct 05 2020 12:37:30 GMT+0000 (Coordinated Universal Time): OK`

I don't see the GUI of grafana.

How can I make run grafana correctly?

**Comment by mikefrank-ca** [comment]
Hello ramogundogdu, this tool won't show anything Grafana related. You will need to add this service datasource through the JSON or SimpleJson plugin.
