### ISSUE TITLE
502 as DS response.

### ISSUE THREAD

**Issue by zakkriel** [bluefrg/jira-grafana-json-datasource#2]
Thanks for creating this plugin!

I 've installed and tested the plugin (can see my user info)
then after setting up the DS in Grafana, I get no info or metrics in the panel..

This is what I get
data:""
status:502
statusText:"Bad Gateway"
xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/1/search"
data:Object
target:""
withCredentials:undefined

as a response.

Help?

Thanks!
Brian

**Comment by mikefrank-ca** [comment]
Can you post the `docker logs` from the jira-grafana-json-datasource container your running?

**Comment by zakkriel** [comment]
Wow, that was fast,
please find it attached.


[LOG.txt](https://github.com/bluefrg/jira-grafana-json-datasource/files/2536755/LOG.txt)

**Comment by mikefrank-ca** [comment]
What's the output of `/test-jira`? Does it see you authenticating to your Jira instance properly?
What version of Jira are you using?
How are you using openresty with this?

**Comment by mikefrank-ca** [comment]
No response received.
