### ISSUE TITLE
thoughts about Jira Server api?

### ISSUE THREAD

**Issue by jnmcfly** [bluefrg/jira-grafana-json-datasource#3]
Hey, 
Im not into programming, but i figured out, that its not possible to "GET" the "/rest/api/2/filter"'s in Jira Server (on-prem). Do you have any ideas, how to do this? 

The only way to "GET" filters is by ".../filter/{id}" or by ".../filter/favourite" documented [here](https://docs.atlassian.com/software/jira/docs/api/REST/7.12.1/#api/2/filter-getFilter)

**Comment by mikefrank-ca** [comment]
Looks like I'd need to switch up the lookup for on-prem Jira to use favorites. This will take some more investigation. Pull-requests welcome.

**Comment by mikefrank-ca** [comment]
The dependencies I'm using don't support Jira running as on-premise.
