### ISSUE TITLE
Problems integrating with Grafana

### ISSUE THREAD

**Issue by ammoqq** [bluefrg/jira-grafana-json-datasource#5]
![Screenshot 2019-03-26 at 17 41 13](https://user-images.githubusercontent.com/11233423/55016333-d3754700-4fee-11e9-968e-a31db750d04b.png)
After adding SimpleJson as datasource & specifying URL ( I verified the test-jira url works correctly ) I cannot see the predefined jira filters. Timeserie dropdown is empty.
grafana used is 6.0.2

Any ideas what is wrong ?

**Comment by mikefrank-ca** [comment]
Do you have any filters made under your user? That list will show your filters if you're using Jira Cloud. Can you attached the output from the container.

**Comment by ammoqq** [comment]
ok found the issue - I do have jira on premise, I can dig into this to add support for on Premise - any specific idea why it cannot be supported as of now ?

**Comment by mikefrank-ca** [comment]
That would explain it. This project relies on jira-connector which uses the Jira Cloud API. Pull requests are welcome.
