### ISSUE TITLE
Cannot run Docker Container 

### ISSUE THREAD

**Issue by kyen29** [bluefrg/jira-grafana-json-datasource#7]
Hello,

I cannot run the docker container and I don't know why. 

Unable to find image 'bluefrg/jira-grafana-json-datasource:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on .... no such host.
See 'docker run --help'.

**Comment by kyen29** [comment]
> Hello,
> 
> I cannot run the docker container and I don't know why.
> 
> Unable to find image 'bluefrg/jira-grafana-json-datasource:latest' locally
> docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on .... no such host.
> See 'docker run --help'.

**Comment by mikefrank-ca** [comment]
Hello, this is an network connectivity issue with your system, not this image. Try looking into something like the following: https://stackoverflow.com/questions/46036152/lookup-registry-1-docker-io-no-such-host
