### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by simSim305** [bluefrg/jira-grafana-json-datasource#8]
Hello bluefrg,

I am new on board and can't start your code. What do I have to adjust to make it work?
node server.js is not working

**Comment by mikefrank-ca** [comment]
I only supply setup instructions for use in a docker container, but to start using cli node, make sure your version matches that of the container, and have your environment variables set.

**Comment by simSim305** [comment]
Hello,

Thanks for the answer.
and what data do I have to replace in the code to work with my jira?

**Comment by simSim305** [comment]
and how I change the port in promtheus from localhost:9090/metrics to jira-port?

**Comment by simSim305** [comment]
if I execute this command he does not recognize the image

docker run -d -p 3000:3000 --name jira-grafana -e JIRA_HOST= -e JIRA_USER= -e JIRA_PASS= bluefrg/jira-grafana-json-datasource

Unable to find image 'bluefrg/jira-grafana-json-datasource:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on .. no such host.
See 'docker run --help'.

**Comment by simSim305** [comment]
if I want to start your code, grafana does not work, because they have the same port. If I change the port, it does not work anymore.
